openapi: "3.0.0"
info:
  version: 0.2
  title: Elo-Ranking-Pairing-System
  description: side project
  contact:
    name: "damody"
    url: "https://www.facebook.com/Remake.AON/"
    email: "t1238142000@gmail.com"
  license:
    name: MIT
    url: http://opensource.org/licenses/MIT
servers:
  - url: http://127.0.0.1:8000/
paths:
  /filter/<clientID>/add_blacklist:
    $ref: /paths/filter/add_blacklist.yaml
  /filter/<clientID>/add_likelist:
    $ref: /paths/filter/add_likelist.yaml
  /filter/<clientID>/remove_blacklist:
    $ref: /paths/filter/remove_blacklist.yaml
  /filter/<clientID>/remove_likelist:
    $ref: /paths/filter/remove_likelist.yaml

  /friend/<clientID>/accept_add:
    $ref: /paths/friend/accept_add.yaml
  /friend/<clientID>/add_friend:
    $ref: /paths/friend/add_friend.yaml
  /friend/<clientID>/reject_add:
    $ref: /paths/friend/reject_add.yaml
  /friend/<clientID>/remove_friend:
    $ref: /paths/friend/remove_friend.yaml

  /room/<clientID>/accept_join:
    $ref: /paths/room/accept_join.yaml
  /room/<clientID>/cancel_queue:
    $ref: /paths/room/cancel_queue.yaml
  /room/<clientID>/close:
    $ref: /paths/room/close.yaml
  /room/<clientID>/create:
    $ref: /paths/room/create.yaml
  /room/<clientID>/invite:
    $ref: /paths/room/invite.yaml
  /room/<clientID>/join:
    $ref: /paths/room/join.yaml
  /room/<clientID>/kick:
    $ref: /paths/room/kick.yaml
  /room/<clientID>/leave:
    $ref: /paths/room/leave.yaml
  /room/<clientID>/prestart:
    $ref: /paths/room/prestart.yaml
  /room/<clientID>/start_queue:
    $ref: /paths/room/start_queue.yaml
  /room/<clientID>/start:
    $ref: /paths/room/start.yaml
    
  /member/<clientID>/login:
    $ref: /paths/member/login.yaml
  /member/<clientID>/logout:
    $ref: /paths/member/logout.yaml
