openapi: "3.0.0"
info:
  version: 0.2
  title: elo rank system 2
  description: side project
  contact:
    name: "damody"
    url: "https://www.facebook.com/Remake.AON/"
    email: "t1238142000@gmail.com"
  license:
    name: MIT
    url: http://opensource.org/licenses/MIT
servers:
  - url: http://127.0.0.1:8000/
paths:
  /room/<clientID>/create:
    $ref: /paths/room/create.yaml
  /room/<clientID>/join:
    $ref: /paths/room/join.yaml
  /room/<clientID>/accept:
    $ref: /paths/room/accept.yaml
  /room/<clientID>/leave:
    $ref: /paths/room/leave.yaml
    
